# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  version:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Increment Commit Tag
        run: |
          # Get the current tag
          current_tag=$(git describe --abbrev=0 --tags)
          echo "Current tag: $current_tag"
          # Extract the major version number
          major=$(echo $current_tag | cut -d "." -f 1 | cut -d "v" -f 2)
          # Extract the minor version number
          minor=$(echo $current_tag | cut -d "." -f 2)
          # Extract the patch number
          patch=$(echo $current_tag | cut -d "." -f 3)
          # Increment the patch number by 1
          new_patch=$((patch + 1))
          # Update the tag
          new_tag="v$major.$minor.$new_patch"
          git tag $new_tag
          git push --tags    
  
  build:
  
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build and deploy package
      run: |
        dotnet pack -c Release --no-restore -p:PackageVersion=$package_version
        dotnet nuget push BTrees/bin/Release/*.nupkg --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/marklauter/index.json
