name: "Increment Tags"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs: 
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Increment Commit Tag
        run: |
          # Get the current tag
          current_tag=$(git describe --abbrev=0 --tags)
          echo "Current tag: $current_tag"
          # Extract the major version number
          major=$(echo $current_tag | cut -d "." -f 1 | cut -d "v" -f 2)
          # Extract the minor version number
          minor=$(echo $current_tag | cut -d "." -f 2)
          # Extract the patch number
          patch=$(echo $current_tag | cut -d "." -f 3)
          # Increment the patch number by 1
          new_patch=$((patch + 1))
          # Update the tag
          new_tag="v$major.$minor.$new_patch"
          git tag $new_tag
          git push --tags      
