name: "Increment Tags"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs: 
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Increment Commit Tag
        run: |
          # Get the current tag
          current_tag=$(git describe --abbrev=0 --tags)
          echo "Current tag: $current_tag"
          current_number=$(echo $current_tag | cut -d "v" -f 2)
          echo "Numeric part of the tag: $current_number"
          # Increment the number by 1
          new_number=$((current_number + 1))
          # Increment the tag by 1
          # Update the tag
          new_tag="v$new_number"
          #new_tag=$((current_tag + 1))
          # Update the tag
          git tag $new_tag
          git push --tags      
